### ISSUE TITLE
Support private instances of GitLab

### ISSUE THREAD

**Issue by AmaanC** [auth0-extensions/auth0-gitlab-deploy#13]
Our code assumes people use gitlab.com here:
https://github.com/auth0-extensions/auth0-gitlab-deploy/blob/master/server/lib/gitlab.js#L18

It'd be nice if this could be configured to be set to a private instance of GitLab for the extension to use for manual deployments. Currently, if the repo doesn't exist on GitLab / the access token is incorrect, a generic "container under quarantine" error is thrown from the sandbox instead of a user-friendly error.

**Comment by neshanjo** [comment]
It would be great to have this functionality since we host our repo on a private GitLab instance.
If you decide not to support other instances, it would be nice to *explicitely state* in the plugin description that only gitlab.com repos are supported. Additionally, you could check that `GITLAB_REPOSITORY` starts with gitlab.com and add this to the description of the field.

**Comment by gunn4r** [comment]
Checking in on this. I was about to start setting this up and connecting to our self hosted gitlab instance but it sounds like it won't work with self hosted / on prem gitlab instances (gitlab enterprise edition).  Is this still the case?

**Comment by fyockm** [comment]
@gunn4r private instance support was implemented with #14.
Sorry for the confusion- this issue should have been closed with that PR.
